### ISSUE TITLE
some general comments

### ISSUE THREAD

**Issue by vivax3794** [ryantupo/christos---the-prisoner-dilemma#1]
* these comments seem out of place: https://github.com/ryantupo/christos---the-prisoner-dilemma/blob/master/christos.py#L3-L15
* some places you use 
```py
if something != True:
```

instead you should be using 
```py
if not something:
```
* instead of `choices[random.randint(0,1)]` you can use `random.choice(choices)` 
* I would recommend using an Enum instead of strings

**Comment by Christo-disc0** [comment]
Aah, thank you very much for that! I'm still quite untrained, so I will definitely study what you sent me. =) cheers!
